name: CI-CD pipeline to AWS #
on:
  push:
    branches:
      - main #Use your own branch here (Might be staging or testing)
jobs:
  deploy:
    name: Push to EC2 Instance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v1

      - name: Deploy to my EC2 instance
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SOURCE: "./"
          REMOTE_HOST: "ec2-54-176-76-99.us-west-1.compute.amazonaws.com"
          REMOTE_USER: "ec2-user"
          TARGET: "/home/ec2-user/napkin-app"
          
      - name: Run commands to change key path and restart server
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ec2-54-176-76-99.us-west-1.compute.amazonaws.com
          username: ec2-user
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            sed -i 's/.*serviceAccount.*/    "serviceAccount": "\/home\/ec2-user\/napkin-app-46c4a-firebase-adminsdk-5ma6a-24d50096c4.json"/' napkin-app/napkin_app/login/views.py 
            sed -i 's/.*serviceAccount.*/    "serviceAccount": "\/home\/ec2-user\/napkin-app-46c4a-firebase-adminsdk-5ma6a-24d50096c4.json"/' napkin-app/napkin_app/napkin/views.py 
            killall python3
            nohup python3 napkin_app/napkin_app/manage.py runserver 0.0.0.0:8000  > log.txt &
         
