name: CI-CD pipeline to AWS #
on:
  push:
    branches:
      - main #Use your own branch here (Might be staging or testing)
jobs:
  deploy:
    name: Push to EC2 Instance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v1

      - name: Deploy to my EC2 instance
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SOURCE: "./"
          REMOTE_HOST: "http://ec2-54-176-76-99.us-west-1.compute.amazonaws.com:8000/"
          REMOTE_USER: "ec2-user"
          TARGET: "/home/ec2-user/napkin-app"