name: CI-CD pipeline to AWS #
on:
  push:
    branches:
      - main #Use your own branch here (Might be staging or testing)
jobs:
  deploy:
    name: Push to EC2 Instance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v1

      - name: Deploy to my EC2 instance
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SOURCE: "./"
          REMOTE_HOST: "ec2-52-53-174-19.us-west-1.compute.amazonaws.com"
          REMOTE_USER: "ubuntu"
          TARGET: "/home/ubuntu/napkin-app"
          
      - name: Run commands to change firebase private key path and restart server
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ec2-52-53-174-19.us-west-1.compute.amazonaws.com
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            sudo pip3 install -r napkin-app/napkin_app/requirements.txt
            sed -i 's/.*serviceAccount.*/    "serviceAccount": "\/home\/ubuntu\/napkin-app-46c4a-firebase-adminsdk-5ma6a-24d50096c4.json"/' napkin-app/napkin_app/login/views.py 
            sed -i 's/.*serviceAccount.*/    "serviceAccount": "\/home\/ubuntu\/napkin-app-46c4a-firebase-adminsdk-5ma6a-24d50096c4.json"/' napkin-app/napkin_app/napkin/views.py
            sudo systemctl restart nginx
            sudo systemctl restart gunicorn
